---
title: "Week 2 - Assignment1"
author: "Reenie Christudass"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r}
## Add 8 and 5
x <- 8
y <- 5
print(paste("Addition of two numbers is:",x+y))
```

```{r}
## Subtract 6 from 22
x <- 22
y <- 6
print(paste("Substraction of two numbers is:",22-6))
```

```{r}
## Add 4 to 6 and divide the result by 2
x <- 4
y <- 6
print(paste("Add 4 to 6 and divide the result by 2:",(x+y)/2))
```

```{r}
## Compute 5 modulo 2
x <- 5
y <- 2
print(paste("Compute 5 modulo 2:",x %% y))
```


```{r}
## Assign the value 82 to the variable x
x <- 82
print(paste("Print assigned variable:",x))
```


```{r}
## Assign the value 41 to the variable y
y <- 45
print(paste("Print assigned variable:",y))
```

```{r}
## Assign the output of x + y to the variable z
## Print z
x <- 8
y <- 5
z <- x+y
print(paste("Addition of two numbers is:",z))
```

```{r}
## Assign the string value "DSC520" to the variable class_name
## Print the value of class_name
class_name <- "DSC520"
print(paste("Print Variable name:",class_name))
```

```{r}
## Assign the string value of TRUE to the variable is_good
## Print the value of is_good
is_good <- "TRUE"
print(paste("Print string Variable name:",is_good))
```


```{r}
## Check the class of the variable is_good using the `class()` function
x <- "is_good"
print(paste("Identify class Variable name:",class(x)))
```


```{r}
## Check the class of the variable z using the `class()` function
x <- "z"
print(paste("Identify class Variable name:",class(z)))
```


```{r}
## Check the class of the variable class_name using the `class()` function
x <- "class_name"
print(paste("Identify class Variable name:",class(x)))
```