---
title: "Week 2 - Assignment2"
author: "Reenie Christudass"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---


```{r}
## Create a numeric vector with the values of 3, 2, 1 using the `c()` function
## Assign the value to a variable named `num_vector`
## Print the vector
num_vector <-  c(3, 2, 1)
print(paste(c("Numeric vector are: ", num_vector), collapse=" "))
```

```{r}
## Create a character vector with the values of "three", "two", "one" "using the `c()` function
## Assign the value to a variable named `char_vector`
## Print the vector
char_vector <-  c("three", "two", "one")
print(paste(c("Character vector are: ", char_vector), collapse=" "))
```
```{r}
## Create a vector called `week1_sleep` representing how many hours slept each night of the week
## Use the values 6.1, 8.8, 7.7, 6.4, 6.2, 6.9, 6.6
week1_sleep <- c(6.1, 8.8, 7.7, 6.4, 6.2, 6.9, 6.6)
print(paste(c("Hours slept each night of the week: ", week1_sleep), collapse=" "))
```

```{r}
## Display the amount of sleep on Tuesday of week 1 by selecting the variable index
weekdays1 <- c( "Sunday" ,"Monday", "Tuesday", "Wednesday", "Thrusday", "Friday", "Saturday")
print(paste("Display the amount of sleep on week 1:",weekdays1[3], week1_sleep[3]))
```
```{r}
## Create a vector called `week1_sleep_weekdays`
## Assign the weekday values using indice slicing
identify_weekdays <- weekdays1[1:5]
week1_sleep_weekdays <- week1_sleep[1:5]
print(paste("Display the amount of sleep for week1:",identify_weekdays, week1_sleep_weekdays))
```
```{r}
## Add the total hours slept in week one using the `sum` function
## Assign the value to variable `total_sleep_week1`
total_sleep_week1 <- sum(week1_sleep[1:7])
print(paste("Display the total amount of sleep for week1:",total_sleep_week1))
```
```{r}
## Create a vector called `week2_sleep` representing how many hours slept each night of the week
## Use the values 7.1, 7.4, 7.9, 6.5, 8.1, 8.2, 8.9
identify_weekdays2 <- c( "Sunday" ,"Monday", "Tuesday", "Wednesday", "Thrusday", "Friday", "Saturday")
week2_sleep <- c(7.1, 7.4, 7.9, 6.5, 8.1, 8.2, 8.9)
print(paste("Display the amount of sleep for week2:",identify_weekdays2, week2_sleep))
```
```{r}
## Add the total hours slept in week two using the sum function
## Assign the value to variable `total_sleep_week2`
total_sleep_week2 <- sum(week2_sleep[1:7])
print(paste("Display the Total amount of sleep for week2:",total_sleep_week2))
```
```{r}
## Determine if the total sleep in week 1 is less than week 2 by using the < operator
#(total_sleep_week2 < total_sleep_week1)
print(paste("Determine if the total sleep in week 1 is less than week 2:",(total_sleep_week2 < total_sleep_week1)))
```
```{r}
## Calculate the mean hours slept in week 1 using the `mean()` function
print(paste("Calculate the mean hours slept in week 1:",mean(total_sleep_week1)))
```
```{r}
## Create a vector called `days` containing the days of the week.
## Start with Sunday and end with Saturday
days <- c( "Sunday" ,"Monday", "Tuesday", "Wednesday", "Thrusday", "Friday", "Saturday")
print(paste("Days of week 1:",days))
```

```{r}
## Assign the names of each day to `week1_sleep` and `week2_sleep` using the `names` function and `days` vector
names(week1_sleep) <- c( "Sunday" ,"Monday", "Tuesday", "Wednesday", "Thrusday", "Friday", "Saturday")
names(week2_sleep) <- c( "Sunday" ,"Monday", "Tuesday", "Wednesday", "Thrusday", "Friday", "Saturday")
print(paste("Days of week 1:",names(week1_sleep)))
print(paste("Days of week 2:",names(week2_sleep)))
```
```{r}
## Display the amount of sleep on Tuesday of week 1 by selecting the variable name
week1_sleep[3]
```
```{r}
## Create vector called weekdays from the days vector
weekdays <- days[2:6]
print(paste("Weekdays:",weekdays))
```
```{r}
## Create vector called weekends containing Sunday and Saturday
weekends <- days[7:1]
print(paste("Days vector:",weekends))
```
```{r}
## Calculate the mean about sleep on weekdays for each week
## Assign the values to weekdays1_mean and weekdays2_mean
weekdays1_mean <- mean(week1_sleep[weekdays])
weekdays2_mean <- mean(week2_sleep[weekdays])
print(weekdays1_mean)
print(weekdays2_mean)
```


```{r}
## Using the weekdays1_mean and weekdays2_mean variables,
## see if weekdays1_mean is greater than weekdays2_mean using the `>` operator
#weekdays1_mean > weekdays2_mean
print(paste("Is weekdays1_mean is greater than weekdays2_mean:",weekdays1_mean > weekdays2_mean))
```
```{r}
## Determine how many days in week 1 had over 8 hours of sleep using the `>` operator
# <- c(6.1, 8.8, 7.7, 6.4, 6.2, 6.9, 6.6)
#length(week1_sleep[week1_sleep > 8])
print(paste("Count the days in week 1 had over 8 hours of sleep:",length(week1_sleep[week1_sleep > 8])))
```
```{r}
## Create a matrix from the following three vectors
student01 <- c(100.0, 87.1)
student02 <- c(77.2, 88.9)
student03 <- c(66.3, 87.9)


students_combined <- c(student01, student02, student03)
grades <- matrix(students_combined,  nrow = 3, byrow = TRUE)

print(grades)

```
```{r}
## Add a new student row with `rbind()`
student04 <- c(95.2, 94.1)
students_combined <- rbind(student01, student02, student03, student04)
grades <- matrix(students_combined, nrow = 4, byrow = TRUE)

rownames(grades) <- c("student01", "student02", "student03", "student04")
colnames(grades) <- c("assignment01", "assignment02")
print(grades)

```
```{r}
## Add a new assignment column with `cbind()`
assignment04 <- c(92.1, 84.3, 75.1, 97.8)
grades <- cbind(grades, assignment04)
print(grades)

```
```{r}
## Add the following names to columns and rows using `rownames()` and `colnames()`
assignments <- c("Assignment 1", "Assignment 2", "Assignment 3")
students <- c("Florinda Baird", "Jinny Foss", "Lou Purvis", "Nola Maloney")

colnames(grades) <- c("Assignment 1", "Assignment 2", "Assignment 3")
rownames(grades) <- c("Florinda Baird", "Jinny Foss", "Lou Purvis", "Nola Maloney")
print(grades)
```
```{r}
## Total points for each assignment using `colSums()`
colSums(grades)
```
```{r}
## Total points for each student using `rowSums()`
rowSums(grades)
```
```{r}
## Matrix with 10% and add it to grades
weighted_grades <- grades * 0.1 + grades
weighted_grades
```
```{r}
## Create a factor of book genres using the genres_vector
## Assign the factor vector to factor_genre_vector
genres_vector <- c("Fantasy", "Sci-Fi", "Sci-Fi", "Mystery", "Sci-Fi", "Fantasy")
factor_genre_vector <- factor(genres_vector)
print(factor_genre_vector)
```

```{r}
## Use the `summary()` function to print a summary of `factor_genre_vector`
summary(factor_genre_vector)
```

```{r}
## Create ordered factor of book recommendations using the recommendations_vector
## `no` is the lowest and `yes` is the highest
recommendations_vector <- c("neutral", "no", "no", "neutral", "yes")
factor_recommendations_vector <- factor(
  recommendations_vector,
  ordered = TRUE,
  levels = c("no", "neutral", "yes")
)
factor_recommendations_vector
```
```{r}
## Use the `summary()` function to print a summary of `factor_recommendations_vector`
summary(factor_recommendations_vector)
```

```{r}
## Using the built-in `mtcars` dataset, view the first few rows using the `head()` function
head(iris)
```
```{r}
## Using the built-in mtcars dataset, view the last few rows using the `tail()` function
tail(iris)
```
```{r}
## Create a dataframe called characters_df using the following information from LOTR
name <- c("Aragon", "Bilbo", "Frodo", "Galadriel", "Sam", "Gandalf", "Legolas", "Sauron", "Gollum")
race <- c("Men", "Hobbit", "Hobbit", "Elf", "Hobbit", "Maia", "Elf", "Maia", "Hobbit")
in_fellowship <- c(TRUE, FALSE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE)
ring_bearer <- c(FALSE, TRUE, TRUE, FALSE, TRUE, TRUE, FALSE, TRUE, TRUE)
age <- c(88, 129, 51, 7000, 36, 2019, 2931, 7052, 589)

characters_df <- data.frame(name,race,in_fellowship,ring_bearer,age)
print(characters_df)
```
```{r}
## Sorting the characters_df by age using the order function and assign the result to the sorted_characters_df
sorted_characters_df <- characters_df[order(age),]
## Use `head()` to output the first few rows of `sorted_characters_df`
head(sorted_characters_df)
```
```{r}
## Select all of the ring bearers from the dataframe and assign it to ringbearers_df
ringbearers_df <- characters_df[characters_df$ring_bearer == TRUE,]
## Use `head()` to output the first few rows of `ringbearers_df`
head(ringbearers_df)
```