---
title: "DSC520_Week3_Assignment03"
author: "Reenie Christudass"
date: '2022-06-24'
output:
  pdf_document: default
  html_document: default
---

```{r}
## Load the ggplot2 package
install.packages("ggplot2", repos="http://cran.us.r-project.org")
library(ggplot2)
theme_set(theme_minimal())
```
```{r}
## Set the working directory to the root of your DSC 520 directory
setwd("C:/Users/chris/dsc520")
```

```{r}
## Load the `data/r4ds/heights.csv` to
heights_df <- read.csv("C:/Users/chris/dsc520/data/r4ds/heights.csv")
print(heights_df)
```


```{r}
# https://ggplot2.tidyverse.org/reference/geom_point.html
## Using `geom_point()` create three scatterplots for
## `height` vs. `earn`
ggplot(heights_df, aes(x=height, y=earn)) + geom_point()
## `age` vs. `earn`
ggplot(heights_df, aes(x=age, y=earn)) + geom_point()
## `ed` vs. `earn`
ggplot(heights_df, aes(x=ed, y=earn)) + geom_point()
```

```{r}
## Re-create the three scatterplots and add a regression trend line using
## the `geom_smooth()` function
## `height` vs. `earn`
ggplot(heights_df, aes(x=height, y=earn)) + geom_point() + geom_smooth()
## `age` vs. `earn`
ggplot(heights_df, aes(x=age, y=earn)) + geom_point() + geom_smooth()
## `ed` vs. `earn`
ggplot(heights_df, aes(x=ed, y=earn)) + geom_point() + geom_smooth()
```

```{r}
## Create a scatterplot of `height`` vs. `earn`.  Use `sex` as the `col` (color) attribute
ggplot(heights_df, aes(x=height, y=earn, col=factor(sex))) + geom_point()
```


```{r}
## Using `ggtitle()`, `xlab()`, and `ylab()` to add a title, x label, and y label to the previous plot
## Title: Height vs. Earnings
## X label: Height (Inches)
## Y Label: Earnings (Dollars)
ggplot(heights_df, aes(x=height, y=earn, col=factor(sex))) + geom_point() +
  labs(size= "Nitrogen",
       x = "Height (Inches)",
       y = "Earnings (Dollars)",
       title = "Height vs. Earnings")
```


```{r}
# https://ggplot2.tidyverse.org/reference/geom_histogram.html
## Create a histogram of the `earn` variable using `geom_histogram()`
ggplot(heights_df, aes(earn)) + geom_histogram()
```
```{r}
## Create a histogram of the `earn` variable using `geom_histogram()`
## Use 10 bins
ggplot(heights_df, aes(earn)) + geom_histogram(bins=10)
```

```{r}
# https://ggplot2.tidyverse.org/reference/geom_density.html
## Create a kernel density plot of `earn` using `geom_density()`
ggplot(heights_df, aes(earn)) +  geom_density()
```