---
title: "DSC520_Week4_Assignment01"
author: "Reenie Christudass"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r}
library(crayon)
library(dplyr)
library(tidyr)
```


```{r}
library(readxl)
df <- read_excel("C:/Users/chris/dsc520/data/week-7-housing.xlsx")
cat(blue("Read the Week 7 Housing excel document\n"))
```

```{r}
## Summary of each column
cat(blue("Summary of variables in the dataset\n"))
summary(df)
```
```{r}
##Remove space in the column name
cat(blue("Remove space in the column name"  ))
names(df) <- sub(" ", "_", names(df))
head(df)
```
```{r}
##Use the aggregate function on a variable in your dataset
group_mean <- aggregate(Sale_Price ~ year_built   , data = df, FUN = sum) 
head(group_mean)
```

```{r}
cat(blue("Seperate the Sale_Date into three variables Year, Month, Date\n"))
df <- df %>% separate(Sale_Date, c('Year', 'Month','Date'))
head(df)
```

```{r}
## Re-Create the Column Sale_price
cat(blue("Re-Create the Column Sale_price\n"))
df$Sale_Date <- paste(df$Year,"-",df$Month,"-",df$Date)
head(df)
```

```{r}
##Re-locate the Column Sale_Date in front of Sale_Price
cat(blue("Re-locate the Column Sale_Date in front of Sale_Price\n"))
df %>% relocate(Sale_Date, .before = Sale_Price)

```


```{r}
##perform a modification to the data, and then bring it back together
df <-dplyr::select(df, -c('Year', 'Month','Date'))
df
```

```{r}
## Identify if there are any outliers
cat(blue("Mean of the variable bedrooms\n"))
mean(df$bedrooms)
cat(blue("Median of the variable bedrooms\n"))
median(df$bedrooms)
cat(blue("Quantile of the variable bedrooms\n"))
quantile(df$bedrooms)

```

```{r}
cat(blue("Outliers of the variable bedrooms\n"))
boxplot(df$bedrooms,
  ylab = "bedrooms",
  main = "Boxplot of bedrooms \n"
)

```
```{r}
cat(blue("Outliers of the variable bedrooms\n"))
out <- boxplot.stats(df$bedrooms)$out
out
```

```{r}

hist(df$bedrooms)
cat(blue("Summary of the variable bedrooms\n"))
summary(df$bedrooms)

```






