---
title: "DSC520_Week6_Assignment00"
author: "Reenie Christudass"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---


```{r}
library(ggplot2)
library(dplyr)
```

```{r}
## Load the ggplot2 package
theme_set(theme_minimal())
```

```{r}
## Set the working directory to the root of your DSC 520 directory
setwd("C:/Users/chris/dsc520")
```

```{r}
## Load the `data/r4ds/heights.csv` to
heights_df <- read.csv("C:/Users/chris/dsc520/data/r4ds/heights.csv")
head(heights_df)
```

```{r}
# https://ggplot2.tidyverse.org/reference/geom_boxplot.html
## Create boxplots of sex vs. earn and race vs. earn using `geom_point()` and `geom_boxplot()`
## sex vs. earn
ggplot(heights_df, aes(x=sex, y=earn)) + geom_point()+ geom_boxplot()
## race vs. earn
ggplot(heights_df, aes(x=race, y=earn)) + geom_point()+ geom_boxplot()
```


```{r}
# https://ggplot2.tidyverse.org/reference/geom_bar.html
## Using `geom_bar()` plot a bar chart of the number of records for each `sex`
ggplot(heights_df, aes(sex)) + geom_bar()
```


```{r}
## Using `geom_bar()` plot a bar chart of the number of records for each race
ggplot(heights_df, aes(race)) + geom_bar()
```

```{r}
## Create a horizontal bar chart by adding `coord_flip()` to the previous plot
ggplot(heights_df, aes(race)) + geom_bar() + coord_flip()
```

```{r}
# https://www.rdocumentation.org/packages/ggplot2/versions/3.3.0/topics/geom_path
## Load the file `"data/nytimes/covid-19-data/us-states.csv"` and
## assign it to the `covid_df` dataframe
covid_df <- read.csv("C:/Users/chris/dsc520/data/nytimes/covid-19-data/us-states.csv")
head(covid_df)
```

```{r}
## Parse the date column using `as.Date()``
covid_df$date <- as.Date(covid_df$date)
```

```{r}
## Create three dataframes named `california_df`, `ny_df`, and `florida_df`
## containing the data from California, New York, and Florida
california_df <- covid_df[ which( covid_df$state == "California"), ]
ny_df <- covid_df[ which( covid_df$state == "New York"), ]
florida_df <- covid_df[ which( covid_df$state == "Florida"), ]
head(california_df)
head(ny_df)
head(florida_df)
```



```{r}
## Plot the number of cases in Florida using `geom_line()`
ggplot(data=florida_df, aes(x=cases, y=date, group=1)) + geom_line()
```


```{r}
## Add lines for New York and California to the plot
ggplot(data=ny_df, aes(x=state, group=1)) +
  geom_line(aes(y = deaths)) +
  geom_line(data=ny_df, aes(y = deaths)) +
  geom_line(data=california_df, aes(y = deaths))
```


```{r}
## Use the colors "darkred", "darkgreen", and "steelblue" for Florida, New York, and California
ggplot(data=ny_df, aes(x=state, group=1)) +
  geom_line(aes(y = deaths)) +
  geom_line(data=ny_df, aes(y = deaths) ,color="darkgreen") +
  geom_line(data=california_df, aes(y = deaths) ,color="steelblue")+
  geom_line(data=florida_df, aes(y = deaths),color="darkred")
```



```{r}
## Add a legend to the plot using `scale_colour_manual`
## Add a blank (" ") label to the x-axis and the label "Cases" to the y axis


ggplot(data=ny_df, aes(x=state, group=1)) +
  geom_line(aes(y = cases, colour = "New York")) +
  geom_line(data=california_df, aes(y = cases,colour="California")) +
  geom_line(data=florida_df, aes(y = cases, colour="Florida")) +
  scale_colour_manual(values = c("darkgreen", "steelblue", "darkred") ,  breaks = c(9000, 1000000, 1000000)) +
  xlab("State") + ylab("Cases")
```



```{r}
## Scale the y axis using `scale_y_log10()`

ggplot(data=ny_df, aes(x=state, group=1)) +
  geom_line(aes(y = cases, colour = "New York")) +
  geom_line(data=california_df, aes(y = cases,colour="California")) +
  geom_line(data=florida_df, aes(y = cases, colour="Florida")) +
  scale_colour_manual(values = c("darkgreen", "steelblue", "darkred") ,  breaks = c(9000, 1000000, 1000000)) +
  xlab("State") + ylab("cases") + scale_y_log10()

```